regRecUI/regRecUI/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/", to: "home#start", as: 'home'
  get "/add_data", to: "add_data#start", as: 'add_data_start'
  get "/add_data/node", to: "add_data#node_start", as: 'add_node_start'
  post "/add_data/node", to: "add_data#submit_node", as: 'submit_node'
  get "/add_data/node/success", to: "add_data#submit_node_success", as: 'submit_node_success'
  get "/add_data/edge", to: "add_data#edge_start", as: 'add_edge_start'
  post "/add_data/edge", to: "add_data#submit_add_edge", as: 'add_edge_submit'
  get "/add_data/edge/success", to: "add_data#add_edge_success", as: 'add_edge_success'
  get "/add_data/reg_piece", to: "add_data#reg_piece_start", as: 'add_reg_piece_start'
  post "/add_data/reg_piece", to: "add_data#submit_reg_piece", as: 'add_reg_submit'
  get "/add_data/reg_piece/success", to: "add_data#add_reg_piece_success", as: 'add_reg_success'

  get "/view_data", to: "view_data#start", as: 'view_data_home'
  get "/view_data/node", to: "view_data#view_node", as: 'view_node_page'

  get "/update_weighting", to: "update_weighting#start", as: 'update_weight_start'
  post "/update_weighting", to: "update_weighting#submit", as: 'update_weight_submit'

  get "/update_reg_weighting", to: "update_weighting#reg_start", as: 'update_reg_weight_start'
  get "/update_reg_weighting/node", to: "update_weighting#reg_piece_weighting", as: 'update_reg_node_selected'
  post "/update_reg_weighting/node", to: "update_weighting#submit_reg_weight", as: 'update_reg_weight_submit'

  get "/recommendations_v1", to: "recommendation#start_v1", as: 'recommendations_v1'
  get "/recommendations_v1/view", to: "recommendation#recommend_v1", as: 'recommendations_v1_view'

  get "/recommendations_v2", to: "recommendation#start_v2", as: 'recommendations_v2'
  post "/recommendations_v2", to: "recommendation#recommend_v2", as: 'recommendations_v2_submit'
  get "/recommendations_v2/view", to: "recommendation#recommend_v2_view", as: 'recommendations_v2_view'

  get "/error/api", to: "error#api_error", as: 'api_error'


end

regRecUI/regRecUI/app/controllers/update_weighting_controller.rb
class UpdateWeightingController < ApplicationController
  def start
    @user_response = UpdateWeight.new
    response = ApiService.get_all_nodes
    if response.status.eql?200
      all_nodes = JSON.parse(response.body)
    else
      redirect_to api_error_path and return
    end

    @node1 = all_nodes.sample
    @node2 = all_nodes.sample

    while @node1["id"].eql?@node2["id"]
      @node2 = all_nodes.sample
    end
    set_node_pairing(@node1, @node2)
  end

  def submit
    @user_response = UpdateWeight.new(update_weighting_params)
    if @user_response.response.to_i.eql?0
      redirect_to update_weight_start_path and return
    end
    nodes = get_node_pairing
    response = ApiService.get_check_edge_pairing_exists(nodes["node1"]["id"], nodes["node2"]["id"])
    if response.status.eql?200
      edge = JSON.parse(response.body)
    elsif response.status.eql?404
      check = JSON.parse(response.body)
      if check["title"].eql?"EDGE_NOT_FOUND"
        #create edge for pair
        response = ApiService.post_add_edge(nodes["node1"]["id"], nodes["node2"]["id"])
        unless response.status.eql? 200
          redirect_to api_error_path and return
        end
        edge = JSON.parse(response.body)
      else
        redirect_to api_error_path and return
      end
    else
      redirect_to api_error_path and return
    end

    response = ApiService.post_update_edge_weight(edge["id"], @user_response.response.to_i)
    if response.status.eql?200
      redirect_to update_weight_start_path
    else
      redirect_to api_error_path
    end
  end

  def reg_start
    @all_nodes = nil
    response = ApiService.get_all_nodes
    if response.status.eql?200
      @all_nodes = JSON.parse(response.body)
    else
      redirect_to api_error_path
    end
  end

  def reg_piece_weighting
    node_id = params[:node]
    set_node_id(node_id)
    response = ApiService.get_node_by_id(node_id)
    if response.status.eql?200
      @node = JSON.parse(response.body)
    else
      redirect_to api_error_path and return
    end
    @user_input = UpdateWeight.new
    response = ApiService.get_node_reg_pieces(node_id)
    if response.status.eql?200
      reg_pieces = JSON.parse(response.body)
    else
      redirect_to api_error_path and return
    end
    @reg_piece = reg_pieces.sample
    set_reg_piece(@reg_piece)
  end

  def submit_reg_weight
    reg_piece = get_reg_piece
    @user_input = UpdateWeight.new(update_weighting_params)

    if @user_input.response.to_i.eql?0
      redirect_to controller: 'update_weighting', action: 'reg_piece_weighting', :node => get_node_id  and return
    end
    response = ApiService.post_update_reg_weight(reg_piece["id"], @user_input.response.to_i)

    if response.status.eql?200
      redirect_to controller: 'update_weighting', action: 'reg_piece_weighting', :node => get_node_id
    else
      redirect_to api_error_path
    end
  end

  private

  def update_weighting_params
    params.require(:update_weight).permit(:response)
  end
end

regRecUI/regRecUI/app/views/update_weighting/reg_piece_weighting.haml
%reg_weighting
  %h1= "This partial registration number reminds you of #{@node["name"]}"
  %h3= "#{@reg_piece["content"]}"
  = form_for @user_input, url: update_reg_weight_submit_path do |form|
    %table{border:1}
      %tr
        %td= "STRONGLY DISAGREE"
        %td= "SOMEWHAT DISAGREE"
        %td= "NEITHER AGREE OR DISAGREE"
        %td= "SOMEWHAT AGREE"
        %td= "STRONGLY AGREE"
      %tr
        %td
          = form.radio_button("response", -50)
        %td
          = form.radio_button("response", -25)
        %td
          = form.radio_button("response", 0)
        %td
          = form.radio_button("response", 25)
        %td
          = form.radio_button("response", 50)
    %br
    = form.submit "Submit"

  = link_to "Back to nodes", update_reg_weight_start_path

regRecUI/regRecUI/app/views/update_weighting/reg_start.haml
%reg_start
  %h1= "For which node?"
  %table
    - @all_nodes.each do |node|
      %tr
        %td= node["name"]
        %td
          = link_to "Choose", update_reg_node_selected_path(:node => node["id"])

regRecUI/regRecUI/app/views/update_weighting/start.haml
%update_weighting
  %h1= "These nodes are closely related topics."
  %h3= "#{@node1["name"]} and #{@node2["name"]}"
  = form_for @user_response, url: update_weight_submit_path do |form|
    %table{border:1}
      %tr
        %td= "STRONGLY DISAGREE"
        %td= "SOMEWHAT DISAGREE"
        %td= "NEITHER AGREE OR DISAGREE"
        %td= "SOMEWHAT AGREE"
        %td= "STRONGLY AGREE"
      %tr
        %td
          = form.radio_button("response", -50)
        %td
          = form.radio_button("response", -25)
        %td
          = form.radio_button("response", 0)
        %td
          = form.radio_button("response", 25)
        %td
          = form.radio_button("response", 50)
    %br
    = form.submit "Submit"