regRecUI/regRecUI/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/", to: "home#start", as: 'home'
  get "/add_data", to: "add_data#start", as: 'add_data_start'
  get "/add_data/node", to: "add_data#node_start", as: 'add_node_start'
  post "/add_data/node", to: "add_data#submit_node", as: 'submit_node'
  get "/add_data/node/success", to: "add_data#submit_node_success", as: 'submit_node_success'
  get "/add_data/edge", to: "add_data#edge_start", as: 'add_edge_start'
  post "/add_data/edge", to: "add_data#submit_add_edge", as: 'add_edge_submit'
  get "/add_data/edge/success", to: "add_data#add_edge_success", as: 'add_edge_success'
  get "/add_data/reg_piece", to: "add_data#reg_piece_start", as: 'add_reg_piece_start'
  post "/add_data/reg_piece", to: "add_data#submit_reg_piece", as: 'add_reg_submit'
  get "/add_data/reg_piece/success", to: "add_data#add_reg_piece_success", as: 'add_reg_success'

  get "/view_data", to: "view_data#start", as: 'view_data_home'
  get "/view_data/node", to: "view_data#view_node", as: 'view_node_page'

  get "/update_weighting", to: "update_weighting#start", as: 'update_weight_start'
  post "/update_weighting", to: "update_weighting#submit", as: 'update_weight_submit'

  get "/update_reg_weighting", to: "update_weighting#reg_start", as: 'update_reg_weight_start'
  get "/update_reg_weighting/node", to: "update_weighting#reg_piece_weighting", as: 'update_reg_node_selected'
  post "/update_reg_weighting/node", to: "update_weighting#submit_reg_weight", as: 'update_reg_weight_submit'

  get "/recommendations_v1", to: "recommendation#start_v1", as: 'recommendations_v1'
  get "/recommendations_v1/view", to: "recommendation#recommend_v1", as: 'recommendations_v1_view'

  get "/recommendations_v2", to: "recommendation#start_v2", as: 'recommendations_v2'
  post "/recommendations_v2", to: "recommendation#recommend_v2", as: 'recommendations_v2_submit'
  get "/recommendations_v2/view", to: "recommendation#recommend_v2_view", as: 'recommendations_v2_view'

  get "/error/api", to: "error#api_error", as: 'api_error'


end

regRecUI/regRecUI/app/controllers/add_data_controller.rb
class AddDataController < ApplicationController
  def start

  end

  def node_start
    @node = AddNode.new
  end

  def submit_node
    @node = AddNode.new(add_node_params)
    response = ApiService.post_add_node(@node.name)
    if response.status.eql?200
      set_node_name(@node.name)
      redirect_to submit_node_success_path
    else
      redirect_to api_error_path
    end
  end

  def submit_node_success
    @add_data_link = add_data_start_path
    @node_name = get_node_name
  end

  def edge_start
    response = ApiService.get_all_nodes
    @all_nodes = nil
    @add_edge = AddEdge.new
    if response.status.eql?200
      @all_nodes = JSON.parse(response.body)
    else
      redirect_to api_error_path
    end
  end

  def submit_add_edge
    @add_edge = AddEdge.new(add_edge_params)
    response = ApiService.post_add_edge(@add_edge.nodeId1, @add_edge.nodeId2)
    if response.status.eql?200
      set_edge(JSON.parse(response.body))
      redirect_to add_edge_success_path
    else
      redirect_to api_error_path
    end
  end

  def add_edge_success
    @add_data_link = add_data_start_path
    @edge = get_edge
  end

  def reg_piece_start
    @add_reg_piece = AddRegPiece.new
    @all_nodes = nil
    response = ApiService.get_all_nodes
    if response.status.eql?200
      @all_nodes = JSON.parse(response.body)
    else
      redirect_to api_error_path
    end
  end

  def submit_reg_piece
    @add_reg_piece = AddRegPiece.new(add_reg_piece_params)
    response = ApiService.post_add_reg_piece(@add_reg_piece.content, @add_reg_piece.parentNodeId)
    if response.status.eql?200
      set_reg_piece(JSON.parse(response.body))
      redirect_to add_reg_success_path
    else
      redirect_to api_error_path
    end
  end

  def add_reg_piece_success
    @add_data_link = add_data_start_path
    @reg_piece = get_reg_piece
  end

  private

  def add_node_params
    params.require(:add_node).permit(:name)
  end

  def add_edge_params
    params.require(:add_edge).permit(:nodeId1, :nodeId2)
  end

  def add_reg_piece_params
    params.require(:add_reg_piece).permit(:content, :parentNodeId)
  end
end

regRecUI/regRecUI/app/views/add_data/add_edge_success.haml
%add_node_success
  %h1= "Added new edge with ID #{@edge["id"]}"
  %table
    %tr
      %td= @edge["Node1"]["id"]
      %td= @edge["Node1"]["name"]
    %tr
      %td= @edge["Node2"]["id"]
      %td= @edge["Node2"]["name"]

  %a{href: @add_data_link, title: 'Test'} Add more data
  %a{href: home_path} Home

regRecUI/regRecUI/app/views/add_data/add_reg_piece_success.haml
%add_reg_piece_success
  %h1= "Added Reg Piece #{@reg_piece["content"]} at ID #{@reg_piece["id"]}"
  %table
    %tr
      %td= @reg_piece["parent"]["id"]
      %td= @reg_piece["parent"]["name"]
    %tr
      %td= @reg_piece["size"]

  %a{href: @add_data_link, title: 'Test'} Add more data
  %a{href: home_path} Home

regRecUI/regRecUI/app/views/add_data/edge_start.haml
%edge_start
  = form_for @add_edge, url: add_edge_submit_url do |form|
    %tables{ style: "display: flex"}
      %table
        - @all_nodes.each do |node|
          %tr
            %td= node["name"]
            %td
              = form.radio_button("nodeId1", node["id"])
      %table
        - @all_nodes.each do |node|
          %tr
            %td= node["name"]
            %td
              = form.radio_button("nodeId2", node["id"])
    = form.submit

regRecUI/regRecUI/app/views/add_data/node_start.haml
%add_node
  = form_for @node, url: submit_node_path do |form|
    = form.label :name
    = form.text_field :name

    =form.submit

regRecUI/regRecUI/app/views/add_data/reg_piece_start.haml
%reg_piece_start
  = form_for @add_reg_piece, url: add_reg_submit_path do |form|
    %tables{ style: "display: flex"}
      %table
        - @all_nodes.each do |node|
          %tr
            %td= node["name"]
            %td
              = form.radio_button("parentNodeId", node["id"])
    = form.label :content
    = form.text_field :content

    =form.submit

regRecUI/regRecUI/app/views/add_data/start.haml
%add_data
  %a{href: add_node_start_path} Add node
  %a{href: add_edge_start_path} Add edge
  %a{href: add_reg_piece_start_path} Add reg piece

regRecUI/regRecUI/app/views/add_data/submit_node_success.haml
%submit_node_success
  %h1= "Node with name #{@node_name} added!"

  %a{href: @add_data_link, title: 'Test'} Add data
  %a{href: home_path} Home